name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security-scan-sca:
    runs-on: ubuntu-latest
    steps:
    - name: Conventional Commit Lint
      uses: tnbozman/devsecops-platform/git/conventional-commit-action.yaml@main
